/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/Button.vue')['default']
    IconTablerHome: typeof import('~icons/tabler/home')['default']
    IconTablerLoader2: typeof import('~icons/tabler/loader2')['default']
    Input: typeof import('./src/components/ui/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./src/components/ui/Switch.vue')['default']
  }
}
