export type Variant = 'primary' | 'secondary' | 'warning' | 'success' | 'danger'
export type Rounded = 'none' | 'sm' | 'md' | 'lg' | 'full'
export type Size = 'sm' | 'md' | 'lg'
export type ButtonType = 'button' | 'submit' | 'reset'
export type InputType = 'text' | 'password' | 'textarea'
export type Placement = 'left' | 'right' | 'top' | 'bottom'